# Generated by Django 4.2.7 on 2023-12-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_galery_newsimages_slider_delete_newsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
