# Generated by Django 4.2.7 on 2024-01-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0005_message_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
